export const SEARCHCONFIG_GET = 'SEARCHCONFIG_GET';
export const SEARCHCONFIG_RECEIVE = 'SEARCHCONFIG_RECEIVE';
export const SEARCHCONFIG_FILTERING_METHOD_SELECT_VALUE = 'SEARCHCONFIG_FILTERING_METHOD_SELECT_VALUE';
export const SEARCHCONFIG_COMPARISON_METHOD_SELECT_VALUE = 'SEARCHCONFIG_COMPARISON_METHOD_SELECT_VALUE';
export const SEARCHCONFIG_QUERY_UPDATE = 'SEARCHCONFIG_QUERY_UPDATE';